- project:
    check:
      jobs:
        - ironic-dsvm-standalone
        - ironic-dsvm-standalone-queens
        - ironic-dsvm-standalone-pike
        - ironic-tempest-dsvm-ipa-wholedisk-bios-agent_ipmitool-tinyipa
        - ironic-tempest-dsvm-ipa-wholedisk-bios-agent_ipmitool-tinyipa-queens
        - ironic-tempest-dsvm-ipa-wholedisk-bios-agent_ipmitool-tinyipa-pike
        - ironic-tempest-dsvm-ipa-wholedisk-bios-agent_ipmitool-tinyipa-ocata
        - ironic-tempest-dsvm-ironic-inspector
        - ironic-tempest-dsvm-ironic-inspector-queens
        - ironic-tempest-dsvm-ironic-inspector-pike
        - ironic-tempest-dsvm-ironic-inspector-ocata
        - ironic-inspector-tempest-dsvm-discovery
        - ironic-inspector-tempest-dsvm-discovery-queens
        - ironic-inspector-tempest-dsvm-discovery-pike
        - ironic-inspector-tempest-dsvm-discovery-ocata
    gate:
      jobs:
        - ironic-dsvm-standalone
        - ironic-dsvm-standalone-queens
        - ironic-dsvm-standalone-pike
        - ironic-tempest-dsvm-ipa-wholedisk-bios-agent_ipmitool-tinyipa
        - ironic-tempest-dsvm-ipa-wholedisk-bios-agent_ipmitool-tinyipa-queens
        - ironic-tempest-dsvm-ipa-wholedisk-bios-agent_ipmitool-tinyipa-pike
        - ironic-tempest-dsvm-ipa-wholedisk-bios-agent_ipmitool-tinyipa-ocata
        - ironic-tempest-dsvm-ironic-inspector
        - ironic-tempest-dsvm-ironic-inspector-queens
        - ironic-tempest-dsvm-ironic-inspector-pike
        - ironic-tempest-dsvm-ironic-inspector-ocata
        - ironic-inspector-tempest-dsvm-discovery
        - ironic-inspector-tempest-dsvm-discovery-queens
        - ironic-inspector-tempest-dsvm-discovery-pike
        - ironic-inspector-tempest-dsvm-discovery-ocata
