- project:
    check:
      jobs:
        - ironic-dsvm-standalone
        - ironic-dsvm-standalone-queens
        - ironic-dsvm-standalone-pike
        - ironic-tempest-dsvm-ipa-wholedisk-agent_ipmitool-tinyipa-multinode
        - ironic-tempest-dsvm-ipa-wholedisk-agent_ipmitool-tinyipa-multinode-queens
        - ironic-tempest-dsvm-ipa-wholedisk-agent_ipmitool-tinyipa-multinode-pike
        - ironic-tempest-dsvm-ipa-wholedisk-agent_ipmitool-tinyipa-multinode-ocata
        - ironic-tempest-dsvm-ironic-inspector
        - ironic-tempest-dsvm-ironic-inspector-queens
        - ironic-tempest-dsvm-ironic-inspector-pike
        - ironic-tempest-dsvm-ironic-inspector-ocata
    gate:
      jobs:
        - ironic-dsvm-standalone
        - ironic-dsvm-standalone-queens
        - ironic-dsvm-standalone-pike
        - ironic-tempest-dsvm-ipa-wholedisk-agent_ipmitool-tinyipa-multinode
        - ironic-tempest-dsvm-ipa-wholedisk-agent_ipmitool-tinyipa-multinode-queens
        - ironic-tempest-dsvm-ipa-wholedisk-agent_ipmitool-tinyipa-multinode-pike
        - ironic-tempest-dsvm-ipa-wholedisk-agent_ipmitool-tinyipa-multinode-ocata
        - ironic-tempest-dsvm-ironic-inspector
        - ironic-tempest-dsvm-ironic-inspector-queens
        - ironic-tempest-dsvm-ironic-inspector-pike
        - ironic-tempest-dsvm-ironic-inspector-ocata
